<video class="large-hero__video-bg" playsinline autoplay muted loop poster="https://odcv-ac97.kxcdn.com/oasis-intro-video-cover.jpg">
        <source src="https://odcv-ac97.kxcdn.com/oasis-intro-short-hq.mp4" type="video/mp4">
        <source src="https://odcv-ac97.kxcdn.com/oasis-intro-short-hq.ogv" type="video/ogg">
        <source src="https://odcv-ac97.kxcdn.com/oasis-intro-short-hq.webm" type="video/webm">
      </video> 
      <!-- /.large_hero__video-bg -->