<div class="basic-page__hero-wrapper">
  <div class="basic-page__hero large-hero large-hero--smaller" style="background: url('https://odcv-ac97.kxcdn.com/<?= $videoSource->video_name ?>-video-cover.jpg') no-repeat center center;background-size:cover;">
    
    <video class="large-hero__video-bg" autoplay muted loop>
      <source src="<?= $videoSource->bg_video_url ?>" type="video/mp4" poster="<?= $videoSource->bg_video_poster_url ?>">
    </video>
        <!-- /.large_hero__video-bg -->
  </div>
  <!-- /.basic-page__hero -->
</div>
<!-- /.basic-page__hero-wrapper -->