<script src="<?= $config->urls->templates ?>app/temp/scripts/App.js"></script>
<?php if ($page->template == 'typical-day') : ?>
<script src="<?= $config->urls->templates ?>app/temp/scripts/jquery-1.9.1.min.js"></script>
<script src="<?= $config->urls->templates ?>app/temp/scripts/jquery.flexslider-min.js"></script>
<script src="<?= $config->urls->templates ?>app/temp/scripts/typical-day.js"></script>
<?php endif; ?>