    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?= $page->title ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="manifest" href="site.webmanifest">
    <link rel="apple-touch-icon" href="icon.png">
    <!-- Place favicon.ico in the root directory -->

    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
    <script>
      WebFont.load({
        google: {
          families: ['PT Sans', 'Open Sans:300,400,800', 'Josefin Sans']
        }
      });
    </script>

    <script src="<?= $config->urls->templates ?>vendor/fontawesome-all.min.js"></script>

    <link rel="stylesheet" href="<?= $config->urls->templates ?>app/temp/styles/styles.css" />