<!--[if lte IE 9]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
    <![endif]-->

    <header class="header">
      <a href="/" class="header__logo"><img src="<?= $config->urls->templates ?>images/oasis-children_logo.svg" alt="Oasis Children Logo" class="header__logo-img" ></a>

      <?php require($config->paths->templates."includes/modules/topnav_hp.inc"); ?>
  
    </header>
    <!-- /.header -->